-- CreateTable
CREATE TABLE "GameTemplateVisit" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "gameTemplateId" INTEGER NOT NULL,

    CONSTRAINT "GameTemplateVisit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "GameTemplatePush" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "gameTemplateId" INTEGER NOT NULL,

    CONSTRAINT "GameTemplatePush_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "GameTemplateVisit" ADD CONSTRAINT "GameTemplateVisit_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GameTemplateVisit" ADD CONSTRAINT "GameTemplateVisit_gameTemplateId_fkey" FOREIGN KEY ("gameTemplateId") REFERENCES "GameTemplate"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GameTemplatePush" ADD CONSTRAINT "GameTemplatePush_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GameTemplatePush" ADD CONSTRAINT "GameTemplatePush_gameTemplateId_fkey" FOREIGN KEY ("gameTemplateId") REFERENCES "GameTemplate"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- View-Related Commands (Generated by ChatGPT)

CREATE VIEW "GameTemplateStatistics" AS
SELECT
    gt.id AS id,
    
    -- Count of undeleted likes
    (SELECT COUNT(*) 
     FROM "GameTemplateLike" gtl 
     WHERE gtl."gameTemplateId" = gt.id AND gtl."deleted" = false) AS "undeletedLikeCount",
    
    -- Count of all likes (including deleted)
    (SELECT COUNT(*) 
     FROM "GameTemplateLike" gtl 
     WHERE gtl."gameTemplateId" = gt.id) AS "historicalLikeCount",
    
    -- Count of undeleted comments
    (SELECT COUNT(*) 
     FROM "GameTemplateComment" gtc 
     WHERE gtc."gameTemplateId" = gt.id AND gtc."deleted" = false) AS "undeletedCommentCount",
    
    -- Count of all comments (including deleted)
    (SELECT COUNT(*) 
     FROM "GameTemplateComment" gtc 
     WHERE gtc."gameTemplateId" = gt.id) AS "historicalCommentCount",
    
    -- Count of child game sessions
    (SELECT COUNT(*) 
     FROM "GameSession" gs 
     WHERE gs."parentTemplateId" = gt.id) AS "childSessionsCount",
    
    -- Count of user actions in child sessions (total scenes - 1 per session)
    (SELECT COALESCE(SUM(gsc."sceneCount" - 1), 0)
     FROM (
         SELECT gs.id, COUNT(s.id) AS "sceneCount"
         FROM "GameSession" gs
         LEFT JOIN "Scene" s ON s."gameSessionId" = gs.id
         WHERE gs."parentTemplateId" = gt.id
         GROUP BY gs.id
     ) gsc) AS "childSessionsUserActionsCount",
    
    -- Count of visits to the template overview page
    (SELECT COUNT(*) 
     FROM "GameTemplateVisit" gtv 
     WHERE gtv."gameTemplateId" = gt.id) AS "visitCount",
    
    -- Count of times this template appears in the Trending Templates View
    (SELECT COUNT(*) 
     FROM "GameTemplatePush" gtp 
     WHERE gtp."gameTemplateId" = gt.id) AS "trendingPushCount"
    
FROM 
    "GameTemplate" gt;
